# Generated by Django 5.0.6 on 2024-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name_plural": "Activities"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
