# Generated by Django 5.0.6 on 2024-06-27 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_public_activity_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityinstance",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
    ]
