# Generated by Django 5.0.6 on 2024-05-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="goals",
            new_name="goal",
        ),
    ]
